version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial 
    working_directory: ~/logger-c
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install cmake -y
      - run:
          name: Build mouse-posyx
          command: |
            mkdir build
            cd build
            cmake ..
            make
workflows:
 version: 2
 build_commits:
   jobs:
     - build
